[build]
  publish = "public/"
  command = "npm run build"

[context.production.environment]
  GATSBY_CONTENTFUL_ENVIRONMENT = 'master'


[context.deploy-preview.environment]
  GATSBY_CONTENTFUL_ENVIRONMENT = 'master'

[context.branch-deploy.environment]
  GATSBY_CONTENTFUL_ENVIRONMENT = 'master'
