[build]
  publish = "public/"
  command = "npm run build"

# Branch deploy context:
# All deploys that are not from a pull/merge request
# or from the production branch will inherit these settings.
[context.branch-deploy]
  command = "npm run build-staging"
[context.branch-deploy.environment]
  NODE_ENV = "development"
