import { SelectOption } from '@modules/common/components/SelectField'

export const COUNTRIES: SelectOption[] = [
  { name: 'United States', value: 'United States' },
  { name: 'Antarctica', value: 'Antarctica' },
  { name: 'Antigua and Barbuda', value: 'Antigua and Barbuda' },
  { name: 'Argentina', value: 'Argentina' },
  { name: 'Australia', value: 'Australia' },
  { name: 'Austria', value: 'Austria' },
  { name: 'Bahamas', value: 'Bahamas' },
  { name: 'Barbados', value: 'Barbados' },
  { name: 'Belgium', value: 'Belgium' },
  { name: 'Bermuda', value: 'Bermuda' },
  { name: 'Bolivia', value: 'Bolivia' },
  { name: 'Brazil', value: 'Brazil' },
  { name: 'Bulgaria', value: 'Bulgaria' },
  { name: 'Cambodia', value: 'Cambodia' },
  { name: 'Cameroon', value: 'Cameroon' },
  { name: 'Canada', value: 'Canada' },
  { name: 'Cape Verde', value: 'Cape Verde' },
  { name: 'Cayman Islands', value: 'Cayman Islands' },
  { name: 'Chile', value: 'Chile' },
  { name: 'China', value: 'China' },
  { name: 'Colombia', value: 'Colombia' },
  { name: 'Cook Islands', value: 'Cook Islands' },
  { name: 'Costa Rica', value: 'Costa Rica' },
  { name: 'Croatia', value: 'Croatia' },
  { name: 'Cuba', value: 'Cuba' },
  { name: 'Cyprus', value: 'Cyprus' },
  { name: 'Czech Republic', value: 'Czech Republic' },
  { name: 'Denmark', value: 'Denmark' },
  { name: 'Fiji', value: 'Fiji' },
  { name: 'Finland', value: 'Finland' },
  { name: 'France', value: 'France' },
  { name: 'Germany', value: 'Germany' },
  { name: 'Greece', value: 'Greece' },
  { name: 'Greenland', value: 'Greenland' },
  { name: 'Hong Kong', value: 'Hong Kong' },
  { name: 'Hungary', value: 'Hungary' },
  { name: 'Iceland', value: 'Iceland' },
  { name: 'India', value: 'India' },
  { name: 'Indonesia', value: 'Indonesia' },
  { name: 'Ireland', value: 'Ireland' },
  { name: 'Israel', value: 'Israel' },
  { name: 'Italy', value: 'Italy' },
  { name: 'Jamaica', value: 'Jamaica' },
  { name: 'Japan', value: 'Japan' },
  { name: 'Kenya', value: 'Kenya' },
  { name: 'Maldives', value: 'Maldives' },
  { name: 'Malta', value: 'Malta' },
  { name: 'Mexico', value: 'Mexico' },
  { name: 'Moldova, Republic of', value: 'Moldova, Republic of' },
  { name: 'Monaco', value: 'Monaco' },
  { name: 'Netherlands', value: 'Netherlands' },
  { name: 'New Caledonia', value: 'New Caledonia' },
  { name: 'New Zealand', value: 'New Zealand' },
  { name: 'Nicaragua', value: 'Nicaragua' },
  { name: 'Norway', value: 'Norway' },
  { name: 'Panama', value: 'Panama' },
  { name: 'Paraguay', value: 'Paraguay' },
  { name: 'Peru', value: 'Peru' },
  { name: 'Philippines', value: 'Philippines' },
  { name: 'Poland', value: 'Poland' },
  { name: 'Portugal', value: 'Portugal' },
  { name: 'Puerto Rico', value: 'Puerto Rico' },
  { name: 'Romania', value: 'Romania' },
  { name: 'Saint Helena', value: 'Saint Helena' },
  { name: 'Serbia', value: 'Serbia' },
  { name: 'Singapore', value: 'Singapore' },
  { name: 'Slovakia', value: 'Slovakia' },
  { name: 'Slovenia', value: 'Slovenia' },
  { name: 'South Africa', value: 'South Africa' },
  { name: 'Spain', value: 'Spain' },
  { name: 'Swaziland', value: 'Swaziland' },
  { name: 'Sweden', value: 'Sweden' },
  { name: 'Switzerland', value: 'Switzerland' },
  { name: 'Thailand', value: 'Thailand' },
  { name: 'Turkey', value: 'Turkey' },
  { name: 'Turks and Caicos Islands', value: 'Turks and Caicos Islands' },
  { name: 'Ukraine', value: 'Ukraine' },
  { name: 'United Arab Emirates', value: 'United Arab Emirates' },
  { name: 'United Kingdom', value: 'United Kingdom' },
  { name: 'Uruguay', value: 'Uruguay' },
  { name: 'Venezuela', value: 'Venezuela' },
  { name: 'Viet Nam', value: 'Viet Nam' },
  { name: 'Virgin Islands, British', value: 'Virgin Islands, British' },
  { name: 'Virgin Islands, U.S.', value: 'Virgin Islands, U.S.' }
]
